import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
// import ServerDarkMode from "../../hooks/use-server-dark-mode";
import ClientProvider from "@/components/clientProvider";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Create New Next app",
    default: "Create Next Appl",
  },
  description: "Generated by create next app",
};

// const theme = await ServerDarkMode();
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-white h-full dark:text-white dark:bg-slate-950 text-slate-950`}
      >
        {/* components in nextjs are server components by default, so whenever you want to make use of client fetures like hooks and cookiesProvider, you have to isolate them in a client component first with "use client" on top before you can now use that component as a parent component to pass the faetures you want to*/}
        <ClientProvider>
          <ThemeProvider attribute="class">
            <div className="mb-10 shadow-md shadow-gray-800 py-10  fixed z-50 top-0 left-0 w-[100%] dark:bg-slate-950 bg-white">
              <Header />
            </div>
            <div className="mx-auto mt-[5%] pt-20 w-[80%]">{children}</div>
          </ThemeProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
